CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTES(
COD_CLIENTE INT PRIMARY KEY auto_increment,
NOME VARCHAR (100) NOT NULL,
ENDEREÇO VARCHAR (100) NOT NULL,
CIDADE VARCHAR (100) NOT NULL,
CEP INT NOT NULL
);

CREATE TABLE PEDIDOS(
NUM_PEDIDO INT PRIMARY KEY auto_increment,
DATA_PEDIDO DATETIME,
ITEM VARCHAR (100) NOT NULL,
VALOR DECIMAL (10.2) NOT NULL,
COD_CLIENTE INT,
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE)
);

INSERT INTO CLIENTES
(NOME, ENDEREÇO, CIDADE, CEP)
VALUES ( "Murilo", "Avenida Guapira", "São Paulo", 02265002);
SELECT * FROM CLIENTES;


INSERT INTO PEDIDOS
(COD_CLIENTE, DATA_PEDIDO, ITEM, VALOR)
VALUES (1, '2025-03-14 20:00:00', 'NOTEBOOK', 1500.00);
SELECT * FROM PEDIDOS;

 